import { QueryProvider } from '@/app/providers/QueryProvider';
import { BottomNav } from '@widgets/bottom-nav';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='en'
			className='dark'
		>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen pb-[var(--bottom-nav-height)]`}
			>
				<QueryProvider>
					<div className='overflow-auto flex-1'>{children}</div>
					<Toaster />
					<BottomNav unreadChats={10} />
				</QueryProvider>
			</body>
		</html>
	);
}
